title: The ELIXIR Training Registry
email: tess-support@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
  TeSS is ELIXIR's training platform, providing a one-stop shop for trainersand trainees to discover 
  online information and content, including training materials, events and interactive tutorials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ElixirTeSS

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

logo: images/logo.png